version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NEXT_PUBLIC_BASE_API_URL=http://localhost:4000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.local
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017
      - CORS_ALLOW_CREDENTIALS=true
    volumes:
      - ./backend/src:/app/src
